FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY index.html /usr/share/nginx/html/index.html
COPY chat.html /usr/share/nginx/html/chat.html
COPY turn-test.html /usr/share/nginx/html/turn-test.html
COPY sw.js /usr/share/nginx/html/sw.js
COPY robots.txt /usr/share/nginx/html/robots.txt
COPY sitemap.xml /usr/share/nginx/html/sitemap.xml
COPY favicon.png /usr/share/nginx/html/favicon.png
COPY favicon.svg /usr/share/nginx/html/favicon.svg
COPY og-image.png /usr/share/nginx/html/og-image.png
COPY css /usr/share/nginx/html/css
COPY js /usr/share/nginx/html/js
